### ISSUE TITLE
Criar evento no Sympla

### ISSUE THREAD

**Issue by Anderson-Karlos** [Grude4J/grude4jsite#18]
Cobrando para viabilizar o coffee-break
Link das inscrições: [https://bit.ly/inscrições-meetup-24-grude4j](https://bit.ly/inscri%C3%A7%C3%B5es-meetup-24-grude4j) 
Evento atualizado usando o flyer definitivo

**Comment by flauberjp** [comment]
Criei o evento no sympla, esta como draft.
@Anderson-Karlos esta como gerente do projeto.

**Comment by flauberjp** [comment]
Precisamos da data do evento pelo menos para divulga-lo de forma genérica.

**Comment by flauberjp** [comment]
Como a data foi definida para o dia 22 de novembro, foi possível concluir a criação do evento no sympla. Link: https://bit.ly/inscricoes-meetup-25-grude4j

Quando tivermos o flyer final, precisamos atualizar a arte e a descrição desse vento.
